set(_CATKIN_CURRENT_PACKAGE "line_follower")
set(line_follower_VERSION "0.0.1")
set(line_follower_MAINTAINER "luoxi <luoxi2024@foxmail.com>")
set(line_follower_PACKAGE_FORMAT "2")
set(line_follower_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "message_generation" "roslib")
set(line_follower_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "roslib")
set(line_follower_BUILDTOOL_DEPENDS "catkin")
set(line_follower_BUILDTOOL_EXPORT_DEPENDS )
set(line_follower_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "message_runtime" "roslib")
set(line_follower_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "message_runtime" "roslib")
set(line_follower_TEST_DEPENDS )
set(line_follower_DOC_DEPENDS )
set(line_follower_URL_WEBSITE "")
set(line_follower_URL_BUGTRACKER "")
set(line_follower_URL_REPOSITORY "")
set(line_follower_DEPRECATED "")