set(_CATKIN_CURRENT_PACKAGE "ucar_2026_strict_mission")
set(ucar_2026_strict_mission_VERSION "0.1.0")
set(ucar_2026_strict_mission_MAINTAINER "U-CAR 2026 Team <team@example.com>")
set(ucar_2026_strict_mission_PACKAGE_FORMAT "2")
set(ucar_2026_strict_mission_BUILD_DEPENDS "actionlib" "cv_bridge" "dynamic_reconfigure" "geometry_msgs" "move_base_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf2_ros")
set(ucar_2026_strict_mission_BUILD_EXPORT_DEPENDS "actionlib" "cv_bridge" "dynamic_reconfigure" "geometry_msgs" "move_base_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf2_ros")
set(ucar_2026_strict_mission_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_strict_mission_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_strict_mission_EXEC_DEPENDS "python3-numpy" "ucar_2026_track_end_stop" "ucar_2026_traffic_light_rknn_test" "flow_end" "actionlib" "cv_bridge" "dynamic_reconfigure" "geometry_msgs" "move_base_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf2_ros")
set(ucar_2026_strict_mission_RUN_DEPENDS "python3-numpy" "ucar_2026_track_end_stop" "ucar_2026_traffic_light_rknn_test" "flow_end" "actionlib" "cv_bridge" "dynamic_reconfigure" "geometry_msgs" "move_base_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf2_ros")
set(ucar_2026_strict_mission_TEST_DEPENDS "python3-nose")
set(ucar_2026_strict_mission_DOC_DEPENDS )
set(ucar_2026_strict_mission_URL_WEBSITE "")
set(ucar_2026_strict_mission_URL_BUGTRACKER "")
set(ucar_2026_strict_mission_URL_REPOSITORY "")
set(ucar_2026_strict_mission_DEPRECATED "")