set(_CATKIN_CURRENT_PACKAGE "ucar_2026_track_end_stop")
set(ucar_2026_track_end_stop_VERSION "0.1.0")
set(ucar_2026_track_end_stop_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_track_end_stop_PACKAGE_FORMAT "2")
set(ucar_2026_track_end_stop_BUILD_DEPENDS "libopencv-dev" "rospy" "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(ucar_2026_track_end_stop_BUILD_EXPORT_DEPENDS "rospy" "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(ucar_2026_track_end_stop_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_track_end_stop_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_track_end_stop_EXEC_DEPENDS "libopencv-dev" "usb_cam" "ucar_controller" "rospy" "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(ucar_2026_track_end_stop_RUN_DEPENDS "libopencv-dev" "usb_cam" "ucar_controller" "rospy" "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(ucar_2026_track_end_stop_TEST_DEPENDS )
set(ucar_2026_track_end_stop_DOC_DEPENDS )
set(ucar_2026_track_end_stop_URL_WEBSITE "")
set(ucar_2026_track_end_stop_URL_BUGTRACKER "")
set(ucar_2026_track_end_stop_URL_REPOSITORY "")
set(ucar_2026_track_end_stop_DEPRECATED "")