// Generated by gencpp from file ucar_2026_competition_speech/Announce.msg
// DO NOT EDIT!


#ifndef UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCE_H
#define UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCE_H

#include <ros/service_traits.h>


#include <ucar_2026_competition_speech/AnnounceRequest.h>
#include <ucar_2026_competition_speech/AnnounceResponse.h>


namespace ucar_2026_competition_speech
{

struct Announce
{

typedef AnnounceRequest Request;
typedef AnnounceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Announce
} // namespace ucar_2026_competition_speech


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucar_2026_competition_speech::Announce > {
  static const char* value()
  {
    return "f3261cee1e2a84f216672d4d9f69791a";
  }

  static const char* value(const ::ucar_2026_competition_speech::Announce&) { return value(); }
};

template<>
struct DataType< ::ucar_2026_competition_speech::Announce > {
  static const char* value()
  {
    return "ucar_2026_competition_speech/Announce";
  }

  static const char* value(const ::ucar_2026_competition_speech::Announce&) { return value(); }
};


// service_traits::MD5Sum< ::ucar_2026_competition_speech::AnnounceRequest> should match
// service_traits::MD5Sum< ::ucar_2026_competition_speech::Announce >
template<>
struct MD5Sum< ::ucar_2026_competition_speech::AnnounceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_2026_competition_speech::Announce >::value();
  }
  static const char* value(const ::ucar_2026_competition_speech::AnnounceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_2026_competition_speech::AnnounceRequest> should match
// service_traits::DataType< ::ucar_2026_competition_speech::Announce >
template<>
struct DataType< ::ucar_2026_competition_speech::AnnounceRequest>
{
  static const char* value()
  {
    return DataType< ::ucar_2026_competition_speech::Announce >::value();
  }
  static const char* value(const ::ucar_2026_competition_speech::AnnounceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucar_2026_competition_speech::AnnounceResponse> should match
// service_traits::MD5Sum< ::ucar_2026_competition_speech::Announce >
template<>
struct MD5Sum< ::ucar_2026_competition_speech::AnnounceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_2026_competition_speech::Announce >::value();
  }
  static const char* value(const ::ucar_2026_competition_speech::AnnounceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_2026_competition_speech::AnnounceResponse> should match
// service_traits::DataType< ::ucar_2026_competition_speech::Announce >
template<>
struct DataType< ::ucar_2026_competition_speech::AnnounceResponse>
{
  static const char* value()
  {
    return DataType< ::ucar_2026_competition_speech::Announce >::value();
  }
  static const char* value(const ::ucar_2026_competition_speech::AnnounceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCE_H
