// Generated by gencpp from file ucar_2026_smart_factory_llm/ReasonPickupOrderResponse.msg
// DO NOT EDIT!


#ifndef UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDERRESPONSE_H
#define UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_2026_smart_factory_llm
{
template <class ContainerAllocator>
struct ReasonPickupOrderResponse_
{
  typedef ReasonPickupOrderResponse_<ContainerAllocator> Type;

  ReasonPickupOrderResponse_()
    : success(false)
    , error_message()
    , announcement_physical()
    , announcement_simulation()
    , announcement_full()
    , pickup_item()
    , pickup_major()
    , pickup_workshop()
    , sim_item()
    , sim_major()
    , sim_workshop()
    , raw_model_reply()  {
    }
  ReasonPickupOrderResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_message(_alloc)
    , announcement_physical(_alloc)
    , announcement_simulation(_alloc)
    , announcement_full(_alloc)
    , pickup_item(_alloc)
    , pickup_major(_alloc)
    , pickup_workshop(_alloc)
    , sim_item(_alloc)
    , sim_major(_alloc)
    , sim_workshop(_alloc)
    , raw_model_reply(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _announcement_physical_type;
  _announcement_physical_type announcement_physical;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _announcement_simulation_type;
  _announcement_simulation_type announcement_simulation;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _announcement_full_type;
  _announcement_full_type announcement_full;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pickup_item_type;
  _pickup_item_type pickup_item;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pickup_major_type;
  _pickup_major_type pickup_major;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pickup_workshop_type;
  _pickup_workshop_type pickup_workshop;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sim_item_type;
  _sim_item_type sim_item;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sim_major_type;
  _sim_major_type sim_major;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sim_workshop_type;
  _sim_workshop_type sim_workshop;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _raw_model_reply_type;
  _raw_model_reply_type raw_model_reply;





  typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReasonPickupOrderResponse_

typedef ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<std::allocator<void> > ReasonPickupOrderResponse;

typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse > ReasonPickupOrderResponsePtr;
typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse const> ReasonPickupOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator1> & lhs, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_message == rhs.error_message &&
    lhs.announcement_physical == rhs.announcement_physical &&
    lhs.announcement_simulation == rhs.announcement_simulation &&
    lhs.announcement_full == rhs.announcement_full &&
    lhs.pickup_item == rhs.pickup_item &&
    lhs.pickup_major == rhs.pickup_major &&
    lhs.pickup_workshop == rhs.pickup_workshop &&
    lhs.sim_item == rhs.sim_item &&
    lhs.sim_major == rhs.sim_major &&
    lhs.sim_workshop == rhs.sim_workshop &&
    lhs.raw_model_reply == rhs.raw_model_reply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator1> & lhs, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_2026_smart_factory_llm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e787d6899f55d92dc505ef388cf2bfb";
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e787d6899f55d92ULL;
  static const uint64_t static_value2 = 0xdc505ef388cf2bfbULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_2026_smart_factory_llm/ReasonPickupOrderResponse";
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string error_message\n"
"# 赛方要求的播报格式（可拆成两句给 TTS）\n"
"string announcement_physical\n"
"string announcement_simulation\n"
"string announcement_full\n"
"# 结构化结果，便于下游记录 / 调试\n"
"string pickup_item\n"
"string pickup_major\n"
"string pickup_workshop\n"
"string sim_item\n"
"string sim_major\n"
"string sim_workshop\n"
"string raw_model_reply\n"
"\n"
;
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_message);
      stream.next(m.announcement_physical);
      stream.next(m.announcement_simulation);
      stream.next(m.announcement_full);
      stream.next(m.pickup_item);
      stream.next(m.pickup_major);
      stream.next(m.pickup_workshop);
      stream.next(m.sim_item);
      stream.next(m.sim_major);
      stream.next(m.sim_workshop);
      stream.next(m.raw_model_reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReasonPickupOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
    s << indent << "announcement_physical: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.announcement_physical);
    s << indent << "announcement_simulation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.announcement_simulation);
    s << indent << "announcement_full: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.announcement_full);
    s << indent << "pickup_item: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pickup_item);
    s << indent << "pickup_major: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pickup_major);
    s << indent << "pickup_workshop: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pickup_workshop);
    s << indent << "sim_item: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sim_item);
    s << indent << "sim_major: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sim_major);
    s << indent << "sim_workshop: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sim_workshop);
    s << indent << "raw_model_reply: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.raw_model_reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDERRESPONSE_H
