set(_CATKIN_CURRENT_PACKAGE "map_goal_picker")
set(map_goal_picker_VERSION "0.1.0")
set(map_goal_picker_MAINTAINER "ucar <ucar@todo.todo>")
set(map_goal_picker_PACKAGE_FORMAT "2")
set(map_goal_picker_BUILD_DEPENDS "roscpp" "geometry_msgs" "tf")
set(map_goal_picker_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "tf")
set(map_goal_picker_BUILDTOOL_DEPENDS "catkin")
set(map_goal_picker_BUILDTOOL_EXPORT_DEPENDS )
set(map_goal_picker_EXEC_DEPENDS "roscpp" "geometry_msgs" "tf")
set(map_goal_picker_RUN_DEPENDS "roscpp" "geometry_msgs" "tf")
set(map_goal_picker_TEST_DEPENDS )
set(map_goal_picker_DOC_DEPENDS )
set(map_goal_picker_URL_WEBSITE "")
set(map_goal_picker_URL_BUGTRACKER "")
set(map_goal_picker_URL_REPOSITORY "")
set(map_goal_picker_DEPRECATED "")