set(_CATKIN_CURRENT_PACKAGE "ucar_2026_qr_speak_test")
set(ucar_2026_qr_speak_test_VERSION "0.1.0")
set(ucar_2026_qr_speak_test_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_qr_speak_test_PACKAGE_FORMAT "2")
set(ucar_2026_qr_speak_test_BUILD_DEPENDS "rospy" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "std_srvs")
set(ucar_2026_qr_speak_test_BUILD_EXPORT_DEPENDS "rospy" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "std_srvs")
set(ucar_2026_qr_speak_test_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_qr_speak_test_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_qr_speak_test_EXEC_DEPENDS "rosgraph" "rospkg" "usb_cam" "image_view" "ucar_qr_decoder" "ucar_controller" "speech_command" "ucar_2026_competition" "rospy" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "std_srvs")
set(ucar_2026_qr_speak_test_RUN_DEPENDS "rosgraph" "rospkg" "usb_cam" "image_view" "ucar_qr_decoder" "ucar_controller" "speech_command" "ucar_2026_competition" "rospy" "geometry_msgs" "nav_msgs" "sensor_msgs" "std_msgs" "std_srvs")
set(ucar_2026_qr_speak_test_TEST_DEPENDS )
set(ucar_2026_qr_speak_test_DOC_DEPENDS )
set(ucar_2026_qr_speak_test_URL_WEBSITE "")
set(ucar_2026_qr_speak_test_URL_BUGTRACKER "")
set(ucar_2026_qr_speak_test_URL_REPOSITORY "")
set(ucar_2026_qr_speak_test_DEPRECATED "")