set(_CATKIN_CURRENT_PACKAGE "factory_sign_ppocr_rknn_test")
set(factory_sign_ppocr_rknn_test_VERSION "0.1.0")
set(factory_sign_ppocr_rknn_test_MAINTAINER "ucar <ucar@todo.todo>")
set(factory_sign_ppocr_rknn_test_PACKAGE_FORMAT "2")
set(factory_sign_ppocr_rknn_test_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs" "cv_bridge")
set(factory_sign_ppocr_rknn_test_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs" "cv_bridge")
set(factory_sign_ppocr_rknn_test_BUILDTOOL_DEPENDS "catkin")
set(factory_sign_ppocr_rknn_test_BUILDTOOL_EXPORT_DEPENDS )
set(factory_sign_ppocr_rknn_test_EXEC_DEPENDS "usb_cam" "image_view" "ucar_2026_competition_speech" "rospy" "sensor_msgs" "std_msgs" "cv_bridge")
set(factory_sign_ppocr_rknn_test_RUN_DEPENDS "usb_cam" "image_view" "ucar_2026_competition_speech" "rospy" "sensor_msgs" "std_msgs" "cv_bridge")
set(factory_sign_ppocr_rknn_test_TEST_DEPENDS )
set(factory_sign_ppocr_rknn_test_DOC_DEPENDS )
set(factory_sign_ppocr_rknn_test_URL_WEBSITE "")
set(factory_sign_ppocr_rknn_test_URL_BUGTRACKER "")
set(factory_sign_ppocr_rknn_test_URL_REPOSITORY "")
set(factory_sign_ppocr_rknn_test_DEPRECATED "")