set(_CATKIN_CURRENT_PACKAGE "ucar_2026_traffic_light_rknn_test")
set(ucar_2026_traffic_light_rknn_test_VERSION "0.2.0")
set(ucar_2026_traffic_light_rknn_test_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_traffic_light_rknn_test_PACKAGE_FORMAT "2")
set(ucar_2026_traffic_light_rknn_test_BUILD_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs" "ucar_2026_competition_speech")
set(ucar_2026_traffic_light_rknn_test_BUILD_EXPORT_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs" "ucar_2026_competition_speech")
set(ucar_2026_traffic_light_rknn_test_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_traffic_light_rknn_test_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_traffic_light_rknn_test_EXEC_DEPENDS "image_view" "python3-pil" "speech_command" "usb_cam" "yolo" "cv_bridge" "rospy" "sensor_msgs" "std_msgs" "ucar_2026_competition_speech")
set(ucar_2026_traffic_light_rknn_test_RUN_DEPENDS "image_view" "python3-pil" "speech_command" "usb_cam" "yolo" "cv_bridge" "rospy" "sensor_msgs" "std_msgs" "ucar_2026_competition_speech")
set(ucar_2026_traffic_light_rknn_test_TEST_DEPENDS )
set(ucar_2026_traffic_light_rknn_test_DOC_DEPENDS )
set(ucar_2026_traffic_light_rknn_test_URL_WEBSITE "")
set(ucar_2026_traffic_light_rknn_test_URL_BUGTRACKER "")
set(ucar_2026_traffic_light_rknn_test_URL_REPOSITORY "")
set(ucar_2026_traffic_light_rknn_test_DEPRECATED "")