// Generated by gencpp from file ucar_2026_competition_speech/AnnounceResponse.msg
// DO NOT EDIT!


#ifndef UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCERESPONSE_H
#define UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_2026_competition_speech
{
template <class ContainerAllocator>
struct AnnounceResponse_
{
  typedef AnnounceResponse_<ContainerAllocator> Type;

  AnnounceResponse_()
    : success(false)
    , speech_text()
    , estimated_duration(0.0)
    , message()  {
    }
  AnnounceResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , speech_text(_alloc)
    , estimated_duration(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _speech_text_type;
  _speech_text_type speech_text;

   typedef float _estimated_duration_type;
  _estimated_duration_type estimated_duration;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AnnounceResponse_

typedef ::ucar_2026_competition_speech::AnnounceResponse_<std::allocator<void> > AnnounceResponse;

typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceResponse > AnnounceResponsePtr;
typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceResponse const> AnnounceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator1> & lhs, const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.speech_text == rhs.speech_text &&
    lhs.estimated_duration == rhs.estimated_duration &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator1> & lhs, const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_2026_competition_speech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d69777e02a5c8cab2cb57cba1ade6ebe";
  }

  static const char* value(const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd69777e02a5c8cabULL;
  static const uint64_t static_value2 = 0x2cb57cba1ade6ebeULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_2026_competition_speech/AnnounceResponse";
  }

  static const char* value(const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string speech_text\n"
"float32 estimated_duration\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.speech_text);
      stream.next(m.estimated_duration);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnounceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_2026_competition_speech::AnnounceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "speech_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.speech_text);
    s << indent << "estimated_duration: ";
    Printer<float>::stream(s, indent + "  ", v.estimated_duration);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCERESPONSE_H
