// Generated by gencpp from file ucar_2026_competition_speech/AnnounceRequest.msg
// DO NOT EDIT!


#ifndef UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCEREQUEST_H
#define UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_2026_competition_speech
{
template <class ContainerAllocator>
struct AnnounceRequest_
{
  typedef AnnounceRequest_<ContainerAllocator> Type;

  AnnounceRequest_()
    : event()
    , item()
    , workshop()
    , decision()
    , text()
    , wait(false)  {
    }
  AnnounceRequest_(const ContainerAllocator& _alloc)
    : event(_alloc)
    , item(_alloc)
    , workshop(_alloc)
    , decision(_alloc)
    , text(_alloc)
    , wait(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _event_type;
  _event_type event;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item_type;
  _item_type item;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _workshop_type;
  _workshop_type workshop;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _decision_type;
  _decision_type decision;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;

   typedef uint8_t _wait_type;
  _wait_type wait;





  typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AnnounceRequest_

typedef ::ucar_2026_competition_speech::AnnounceRequest_<std::allocator<void> > AnnounceRequest;

typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceRequest > AnnounceRequestPtr;
typedef boost::shared_ptr< ::ucar_2026_competition_speech::AnnounceRequest const> AnnounceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator1> & lhs, const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.event == rhs.event &&
    lhs.item == rhs.item &&
    lhs.workshop == rhs.workshop &&
    lhs.decision == rhs.decision &&
    lhs.text == rhs.text &&
    lhs.wait == rhs.wait;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator1> & lhs, const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_2026_competition_speech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5c01b62f0b7bc5ddbf1469bdf6b9ea0";
  }

  static const char* value(const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5c01b62f0b7bc5dULL;
  static const uint64_t static_value2 = 0xdbf1469bdf6b9ea0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_2026_competition_speech/AnnounceRequest";
  }

  static const char* value(const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Competition event: task1, task2, task3, task4, task5, or custom.\n"
"string event\n"
"# Used by task2 and task3.\n"
"string item\n"
"string workshop\n"
"# Used by task4. Accepted aliases include left/right/straight/stop and Chinese names.\n"
"string decision\n"
"# Required by task1 and custom. Ignored by the fixed task2-task5 templates.\n"
"string text\n"
"# Wait until the conservative estimated playback duration has elapsed.\n"
"bool wait\n"
;
  }

  static const char* value(const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
      stream.next(m.item);
      stream.next(m.workshop);
      stream.next(m.decision);
      stream.next(m.text);
      stream.next(m.wait);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnounceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_2026_competition_speech::AnnounceRequest_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.event);
    s << indent << "item: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item);
    s << indent << "workshop: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.workshop);
    s << indent << "decision: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.decision);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
    s << indent << "wait: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wait);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_2026_COMPETITION_SPEECH_MESSAGE_ANNOUNCEREQUEST_H
