// Generated by gencpp from file ucar_2026_smart_factory_llm/ReasonPickupOrder.msg
// DO NOT EDIT!


#ifndef UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDER_H
#define UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDER_H

#include <ros/service_traits.h>


#include <ucar_2026_smart_factory_llm/ReasonPickupOrderRequest.h>
#include <ucar_2026_smart_factory_llm/ReasonPickupOrderResponse.h>


namespace ucar_2026_smart_factory_llm
{

struct ReasonPickupOrder
{

typedef ReasonPickupOrderRequest Request;
typedef ReasonPickupOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReasonPickupOrder
} // namespace ucar_2026_smart_factory_llm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrder > {
  static const char* value()
  {
    return "6f2e4969829f8723b74f2ea5cfb7ffc4";
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrder&) { return value(); }
};

template<>
struct DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrder > {
  static const char* value()
  {
    return "ucar_2026_smart_factory_llm/ReasonPickupOrder";
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrder&) { return value(); }
};


// service_traits::MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest> should match
// service_traits::MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >
template<>
struct MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >::value();
  }
  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest> should match
// service_traits::DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >
template<>
struct DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest>
{
  static const char* value()
  {
    return DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >::value();
  }
  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse> should match
// service_traits::MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >
template<>
struct MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >::value();
  }
  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse> should match
// service_traits::DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >
template<>
struct DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse>
{
  static const char* value()
  {
    return DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrder >::value();
  }
  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDER_H
