// Generated by gencpp from file ucar_2026_smart_factory_llm/ReasonPickupOrderRequest.msg
// DO NOT EDIT!


#ifndef UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDERREQUEST_H
#define UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_2026_smart_factory_llm
{
template <class ContainerAllocator>
struct ReasonPickupOrderRequest_
{
  typedef ReasonPickupOrderRequest_<ContainerAllocator> Type;

  ReasonPickupOrderRequest_()
    : item_a()
    , item_b()
    , item_c()
    , voice_instruction()  {
    }
  ReasonPickupOrderRequest_(const ContainerAllocator& _alloc)
    : item_a(_alloc)
    , item_b(_alloc)
    , item_c(_alloc)
    , voice_instruction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item_a_type;
  _item_a_type item_a;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item_b_type;
  _item_b_type item_b;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item_c_type;
  _item_c_type item_c;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _voice_instruction_type;
  _voice_instruction_type voice_instruction;





  typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReasonPickupOrderRequest_

typedef ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<std::allocator<void> > ReasonPickupOrderRequest;

typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest > ReasonPickupOrderRequestPtr;
typedef boost::shared_ptr< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest const> ReasonPickupOrderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator1> & lhs, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.item_a == rhs.item_a &&
    lhs.item_b == rhs.item_b &&
    lhs.item_c == rhs.item_c &&
    lhs.voice_instruction == rhs.voice_instruction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator1> & lhs, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_2026_smart_factory_llm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69a5ea5bde9f7428407b0f91b89d76ab";
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69a5ea5bde9f7428ULL;
  static const uint64_t static_value2 = 0x407b0f91b89d76abULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_2026_smart_factory_llm/ReasonPickupOrderRequest";
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 三个二维码解析得到的子类名称（与扫描顺序一致即可）\n"
"string item_a\n"
"string item_b\n"
"string item_c\n"
"# 语音唤醒后的完整指令文本（含目标大类）\n"
"string voice_instruction\n"
;
  }

  static const char* value(const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.item_a);
      stream.next(m.item_b);
      stream.next(m.item_c);
      stream.next(m.voice_instruction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReasonPickupOrderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_2026_smart_factory_llm::ReasonPickupOrderRequest_<ContainerAllocator>& v)
  {
    s << indent << "item_a: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item_a);
    s << indent << "item_b: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item_b);
    s << indent << "item_c: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item_c);
    s << indent << "voice_instruction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.voice_instruction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_2026_SMART_FACTORY_LLM_MESSAGE_REASONPICKUPORDERREQUEST_H
