set(_CATKIN_CURRENT_PACKAGE "flow_end")
set(flow_end_VERSION "0.0.0")
set(flow_end_MAINTAINER "ucar <ucar@todo.todo>")
set(flow_end_PACKAGE_FORMAT "2")
set(flow_end_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "image_transport" "tf")
set(flow_end_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "image_transport" "tf")
set(flow_end_BUILDTOOL_DEPENDS "catkin")
set(flow_end_BUILDTOOL_EXPORT_DEPENDS )
set(flow_end_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "ucar_controller" "ucar_camera" "traffic_light_vision" "speech_command" "sensor_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "image_transport" "tf")
set(flow_end_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "ucar_controller" "ucar_camera" "traffic_light_vision" "speech_command" "sensor_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "image_transport" "tf")
set(flow_end_TEST_DEPENDS )
set(flow_end_DOC_DEPENDS )
set(flow_end_URL_WEBSITE "")
set(flow_end_URL_BUGTRACKER "")
set(flow_end_URL_REPOSITORY "")
set(flow_end_DEPRECATED "")