// Generated by gencpp from file line_follower/LineTrack.msg
// DO NOT EDIT!


#ifndef LINE_FOLLOWER_MESSAGE_LINETRACK_H
#define LINE_FOLLOWER_MESSAGE_LINETRACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace line_follower
{
template <class ContainerAllocator>
struct LineTrack_
{
  typedef LineTrack_<ContainerAllocator> Type;

  LineTrack_()
    : header()
    , valid(false)
    , confidence(0.0)
    , image_width(0)
    , image_height(0)
    , center_x_px()
    , center_y_px()
    , lookahead_x_px(0.0)
    , lookahead_y_px(0.0)
    , heading_error_rad(0.0)  {
    }
  LineTrack_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , confidence(0.0)
    , image_width(0)
    , image_height(0)
    , center_x_px(_alloc)
    , center_y_px(_alloc)
    , lookahead_x_px(0.0)
    , lookahead_y_px(0.0)
    , heading_error_rad(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef uint32_t _image_width_type;
  _image_width_type image_width;

   typedef uint32_t _image_height_type;
  _image_height_type image_height;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _center_x_px_type;
  _center_x_px_type center_x_px;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _center_y_px_type;
  _center_y_px_type center_y_px;

   typedef float _lookahead_x_px_type;
  _lookahead_x_px_type lookahead_x_px;

   typedef float _lookahead_y_px_type;
  _lookahead_y_px_type lookahead_y_px;

   typedef float _heading_error_rad_type;
  _heading_error_rad_type heading_error_rad;





  typedef boost::shared_ptr< ::line_follower::LineTrack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_follower::LineTrack_<ContainerAllocator> const> ConstPtr;

}; // struct LineTrack_

typedef ::line_follower::LineTrack_<std::allocator<void> > LineTrack;

typedef boost::shared_ptr< ::line_follower::LineTrack > LineTrackPtr;
typedef boost::shared_ptr< ::line_follower::LineTrack const> LineTrackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_follower::LineTrack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_follower::LineTrack_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_follower::LineTrack_<ContainerAllocator1> & lhs, const ::line_follower::LineTrack_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.confidence == rhs.confidence &&
    lhs.image_width == rhs.image_width &&
    lhs.image_height == rhs.image_height &&
    lhs.center_x_px == rhs.center_x_px &&
    lhs.center_y_px == rhs.center_y_px &&
    lhs.lookahead_x_px == rhs.lookahead_x_px &&
    lhs.lookahead_y_px == rhs.lookahead_y_px &&
    lhs.heading_error_rad == rhs.heading_error_rad;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_follower::LineTrack_<ContainerAllocator1> & lhs, const ::line_follower::LineTrack_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::line_follower::LineTrack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_follower::LineTrack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_follower::LineTrack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_follower::LineTrack_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_follower::LineTrack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_follower::LineTrack_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_follower::LineTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8f2dc59e6af2e2fcb8e42affc92dd20";
  }

  static const char* value(const ::line_follower::LineTrack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8f2dc59e6af2e2fULL;
  static const uint64_t static_value2 = 0xcb8e42affc92dd20ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_follower::LineTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_follower/LineTrack";
  }

  static const char* value(const ::line_follower::LineTrack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_follower::LineTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool valid\n"
"float32 confidence\n"
"uint32 image_width\n"
"uint32 image_height\n"
"float32[] center_x_px\n"
"float32[] center_y_px\n"
"float32 lookahead_x_px\n"
"float32 lookahead_y_px\n"
"float32 heading_error_rad\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::line_follower::LineTrack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_follower::LineTrack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.confidence);
      stream.next(m.image_width);
      stream.next(m.image_height);
      stream.next(m.center_x_px);
      stream.next(m.center_y_px);
      stream.next(m.lookahead_x_px);
      stream.next(m.lookahead_y_px);
      stream.next(m.heading_error_rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineTrack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_follower::LineTrack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_follower::LineTrack_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "image_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_width);
    s << indent << "image_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_height);
    s << indent << "center_x_px[]" << std::endl;
    for (size_t i = 0; i < v.center_x_px.size(); ++i)
    {
      s << indent << "  center_x_px[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.center_x_px[i]);
    }
    s << indent << "center_y_px[]" << std::endl;
    for (size_t i = 0; i < v.center_y_px.size(); ++i)
    {
      s << indent << "  center_y_px[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.center_y_px[i]);
    }
    s << indent << "lookahead_x_px: ";
    Printer<float>::stream(s, indent + "  ", v.lookahead_x_px);
    s << indent << "lookahead_y_px: ";
    Printer<float>::stream(s, indent + "  ", v.lookahead_y_px);
    s << indent << "heading_error_rad: ";
    Printer<float>::stream(s, indent + "  ", v.heading_error_rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_FOLLOWER_MESSAGE_LINETRACK_H
