set(_CATKIN_CURRENT_PACKAGE "traffic_light_vision")
set(traffic_light_vision_VERSION "0.0.1")
set(traffic_light_vision_MAINTAINER "ucar <ucar@example.com>")
set(traffic_light_vision_PACKAGE_FORMAT "2")
set(traffic_light_vision_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs" "std_srvs" "cv_bridge")
set(traffic_light_vision_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs" "std_srvs" "cv_bridge")
set(traffic_light_vision_BUILDTOOL_DEPENDS "catkin")
set(traffic_light_vision_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_vision_EXEC_DEPENDS "speech_command" "python3-numpy" "python3-opencv" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "cv_bridge")
set(traffic_light_vision_RUN_DEPENDS "speech_command" "python3-numpy" "python3-opencv" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "cv_bridge")
set(traffic_light_vision_TEST_DEPENDS "python3-nose")
set(traffic_light_vision_DOC_DEPENDS )
set(traffic_light_vision_URL_WEBSITE "")
set(traffic_light_vision_URL_BUGTRACKER "")
set(traffic_light_vision_URL_REPOSITORY "")
set(traffic_light_vision_DEPRECATED "")