# CMake generated Testfile for 
# Source directory: /home/ucar/instant_ws/src_pure_runtime_ws_v3/src
# Build directory: /home/ucar/instant_ws/build_src_pure_runtime_v3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("tf2_msgs")
subdirs("tf2")
subdirs("map_server")
subdirs("tf2_py")
subdirs("cv_bridge")
subdirs("factory_sign_ppocr_rknn_test")
subdirs("image_view")
subdirs("tf")
subdirs("flow_end")
subdirs("map_goal_picker")
subdirs("simple_navigator")
subdirs("tf2_geometry_msgs")
subdirs("amcl")
subdirs("tf2_sensor_msgs")
subdirs("traffic_light_vision")
subdirs("ucar_2026_competition_speech")
subdirs("ucar_2026_qr_speak_test")
subdirs("ucar_2026_smart_factory_llm")
subdirs("ucar_2026_competition")
subdirs("ucar_2026_strict_mission")
subdirs("ucar_2026_track_end_stop")
subdirs("ucar_camera")
subdirs("ucar_controller")
subdirs("ucar_map")
subdirs("ucar_nav")
subdirs("vision_triggered_navigator")
subdirs("voxel_grid")
subdirs("costmap_2d")
subdirs("nav_core")
subdirs("base_local_planner")
subdirs("clear_costmap_recovery")
subdirs("dwa_local_planner")
subdirs("move_slow_and_clear")
subdirs("my_planner")
subdirs("navfn")
subdirs("global_planner")
subdirs("rotate_recovery")
subdirs("move_base")
subdirs("ydlidar")
subdirs("yolo")
