set(_CATKIN_CURRENT_PACKAGE "ucar_qr_decoder")
set(ucar_qr_decoder_VERSION "0.1.0")
set(ucar_qr_decoder_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_qr_decoder_PACKAGE_FORMAT "2")
set(ucar_qr_decoder_BUILD_DEPENDS "message_generation" "cv_bridge" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(ucar_qr_decoder_BUILD_EXPORT_DEPENDS "cv_bridge" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(ucar_qr_decoder_BUILDTOOL_DEPENDS "catkin")
set(ucar_qr_decoder_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_qr_decoder_EXEC_DEPENDS "message_runtime" "cv_bridge" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(ucar_qr_decoder_RUN_DEPENDS "message_runtime" "cv_bridge" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(ucar_qr_decoder_TEST_DEPENDS )
set(ucar_qr_decoder_DOC_DEPENDS )
set(ucar_qr_decoder_URL_WEBSITE "")
set(ucar_qr_decoder_URL_BUGTRACKER "")
set(ucar_qr_decoder_URL_REPOSITORY "")
set(ucar_qr_decoder_DEPRECATED "")