set(_CATKIN_CURRENT_PACKAGE "vision_triggered_navigator")
set(vision_triggered_navigator_VERSION "0.1.0")
set(vision_triggered_navigator_MAINTAINER "ucar <ucar@todo.todo>")
set(vision_triggered_navigator_PACKAGE_FORMAT "2")
set(vision_triggered_navigator_BUILD_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "actionlib" "tf" "std_msgs" "dynamic_reconfigure" "std_srvs")
set(vision_triggered_navigator_BUILD_EXPORT_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "actionlib" "tf" "std_msgs" "dynamic_reconfigure" "std_srvs")
set(vision_triggered_navigator_BUILDTOOL_DEPENDS "catkin")
set(vision_triggered_navigator_BUILDTOOL_EXPORT_DEPENDS )
set(vision_triggered_navigator_EXEC_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "actionlib" "tf" "std_msgs" "dynamic_reconfigure" "std_srvs")
set(vision_triggered_navigator_RUN_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "actionlib" "tf" "std_msgs" "dynamic_reconfigure" "std_srvs")
set(vision_triggered_navigator_TEST_DEPENDS )
set(vision_triggered_navigator_DOC_DEPENDS )
set(vision_triggered_navigator_URL_WEBSITE "")
set(vision_triggered_navigator_URL_BUGTRACKER "")
set(vision_triggered_navigator_URL_REPOSITORY "")
set(vision_triggered_navigator_DEPRECATED "")