set(_CATKIN_CURRENT_PACKAGE "simple_navigator")
set(simple_navigator_VERSION "0.1.0")
set(simple_navigator_MAINTAINER "ucar <ucar@todo.todo>")
set(simple_navigator_PACKAGE_FORMAT "2")
set(simple_navigator_BUILD_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "actionlib" "tf")
set(simple_navigator_BUILD_EXPORT_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "actionlib" "tf")
set(simple_navigator_BUILDTOOL_DEPENDS "catkin")
set(simple_navigator_BUILDTOOL_EXPORT_DEPENDS )
set(simple_navigator_EXEC_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "actionlib" "tf")
set(simple_navigator_RUN_DEPENDS "rospy" "move_base_msgs" "geometry_msgs" "actionlib" "tf")
set(simple_navigator_TEST_DEPENDS )
set(simple_navigator_DOC_DEPENDS )
set(simple_navigator_URL_WEBSITE "")
set(simple_navigator_URL_BUGTRACKER "")
set(simple_navigator_URL_REPOSITORY "")
set(simple_navigator_DEPRECATED "")