set(_CATKIN_CURRENT_PACKAGE "ucar_2026_smart_factory_llm")
set(ucar_2026_smart_factory_llm_VERSION "0.1.0")
set(ucar_2026_smart_factory_llm_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_smart_factory_llm_PACKAGE_FORMAT "2")
set(ucar_2026_smart_factory_llm_BUILD_DEPENDS "message_generation" "std_msgs" "rospy" "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "ucar_2026_competition_speech")
set(ucar_2026_smart_factory_llm_BUILD_EXPORT_DEPENDS )
set(ucar_2026_smart_factory_llm_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_smart_factory_llm_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_smart_factory_llm_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs" "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "ucar_2026_competition_speech")
set(ucar_2026_smart_factory_llm_RUN_DEPENDS "message_runtime" "rospy" "std_msgs" "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "ucar_2026_competition_speech")
set(ucar_2026_smart_factory_llm_TEST_DEPENDS )
set(ucar_2026_smart_factory_llm_DOC_DEPENDS )
set(ucar_2026_smart_factory_llm_URL_WEBSITE "")
set(ucar_2026_smart_factory_llm_URL_BUGTRACKER "")
set(ucar_2026_smart_factory_llm_URL_REPOSITORY "")
set(ucar_2026_smart_factory_llm_DEPRECATED "")