# CMake generated Testfile for 
# Source directory: /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl
# Build directory: /home/ucar/instant_ws/src3/build_pure/ucar_2026_nav/3rd/navigation/amcl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_amcl_rostest_test_set_initial_pose.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_set_initial_pose.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_set_initial_pose.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/set_initial_pose.xml ")
add_test(_ctest_amcl_rostest_test_set_initial_pose_delayed.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_set_initial_pose_delayed.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_set_initial_pose_delayed.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/set_initial_pose_delayed.xml ")
add_test(_ctest_amcl_rostest_test_basic_localization_stage.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_basic_localization_stage.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_basic_localization_stage.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/basic_localization_stage.xml ")
add_test(_ctest_amcl_rostest_test_global_localization_stage.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_global_localization_stage.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_global_localization_stage.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/global_localization_stage.xml ")
add_test(_ctest_amcl_rostest_test_small_loop_prf.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_small_loop_prf.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_small_loop_prf.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/small_loop_prf.xml ")
add_test(_ctest_amcl_rostest_test_small_loop_crazy_driving_prg.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_small_loop_crazy_driving_prg.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_small_loop_crazy_driving_prg.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/small_loop_crazy_driving_prg.xml ")
add_test(_ctest_amcl_rostest_test_texas_greenroom_loop.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_texas_greenroom_loop.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_texas_greenroom_loop.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/texas_greenroom_loop.xml ")
add_test(_ctest_amcl_rostest_test_rosie_multilaser.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_rosie_multilaser.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_rosie_multilaser.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/rosie_multilaser.xml ")
add_test(_ctest_amcl_rostest_test_texas_willow_hallway_loop.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/amcl/rostest-test_texas_willow_hallway_loop.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl --package=amcl --results-filename test_texas_willow_hallway_loop.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/navigation/amcl/test/texas_willow_hallway_loop.xml ")
