set(_CATKIN_CURRENT_PACKAGE "ucar_2026_qr_speak_test")
set(ucar_2026_qr_speak_test_VERSION "0.1.0")
set(ucar_2026_qr_speak_test_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_qr_speak_test_PACKAGE_FORMAT "2")
set(ucar_2026_qr_speak_test_BUILD_DEPENDS "rospy" "std_msgs")
set(ucar_2026_qr_speak_test_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(ucar_2026_qr_speak_test_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_qr_speak_test_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_qr_speak_test_EXEC_DEPENDS "usb_cam" "image_view" "yolo" "rospy" "std_msgs")
set(ucar_2026_qr_speak_test_RUN_DEPENDS "usb_cam" "image_view" "yolo" "rospy" "std_msgs")
set(ucar_2026_qr_speak_test_TEST_DEPENDS )
set(ucar_2026_qr_speak_test_DOC_DEPENDS )
set(ucar_2026_qr_speak_test_URL_WEBSITE "")
set(ucar_2026_qr_speak_test_URL_BUGTRACKER "")
set(ucar_2026_qr_speak_test_URL_REPOSITORY "")
set(ucar_2026_qr_speak_test_DEPRECATED "")