set(_CATKIN_CURRENT_PACKAGE "ucar_2026_competition")
set(ucar_2026_competition_VERSION "0.1.0")
set(ucar_2026_competition_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_competition_PACKAGE_FORMAT "2")
set(ucar_2026_competition_BUILD_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "nav_msgs" "sensor_msgs" "rospy" "std_msgs" "std_srvs" "ucar_2026_competition_speech" "ucar_2026_smart_factory_llm")
set(ucar_2026_competition_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "nav_msgs" "sensor_msgs" "rospy" "std_msgs" "std_srvs" "ucar_2026_competition_speech" "ucar_2026_smart_factory_llm")
set(ucar_2026_competition_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_competition_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_competition_EXEC_DEPENDS "factory_sign_ppocr_rknn_test" "flow_end" "rosnode" "simple_navigator" "traffic_light_vision" "ucar_camera" "ucar_2026_track_end_stop" "ucar_2026_strict_mission" "ucar_2026_traffic_light_rknn_test" "ucar_nav" "usb_cam" "vision_triggered_navigator" "yolo" "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "nav_msgs" "sensor_msgs" "rospy" "std_msgs" "std_srvs" "ucar_2026_competition_speech" "ucar_2026_smart_factory_llm")
set(ucar_2026_competition_RUN_DEPENDS "factory_sign_ppocr_rknn_test" "flow_end" "rosnode" "simple_navigator" "traffic_light_vision" "ucar_camera" "ucar_2026_track_end_stop" "ucar_2026_strict_mission" "ucar_2026_traffic_light_rknn_test" "ucar_nav" "usb_cam" "vision_triggered_navigator" "yolo" "actionlib" "actionlib_msgs" "geometry_msgs" "move_base_msgs" "nav_msgs" "sensor_msgs" "rospy" "std_msgs" "std_srvs" "ucar_2026_competition_speech" "ucar_2026_smart_factory_llm")
set(ucar_2026_competition_TEST_DEPENDS )
set(ucar_2026_competition_DOC_DEPENDS )
set(ucar_2026_competition_URL_WEBSITE "")
set(ucar_2026_competition_URL_BUGTRACKER "")
set(ucar_2026_competition_URL_REPOSITORY "")
set(ucar_2026_competition_DEPRECATED "")