set(yolo_SETUP_PY_SETUP_MODULE "setuptools")
set(yolo_SETUP_PY_VERSION "0.1.0")
set(yolo_SETUP_PY_SCRIPTS "")
set(yolo_SETUP_PY_PACKAGES "yolo_tools")
set(yolo_SETUP_PY_PACKAGE_DIRS "src/yolo_tools")
set(yolo_SETUP_PY_MODULES "")
set(yolo_SETUP_PY_MODULE_DIRS "")