set(_CATKIN_CURRENT_PACKAGE "ucar_2026_competition_speech")
set(ucar_2026_competition_speech_VERSION "0.1.0")
set(ucar_2026_competition_speech_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_competition_speech_PACKAGE_FORMAT "2")
set(ucar_2026_competition_speech_BUILD_DEPENDS "message_generation" "rospy" "std_msgs")
set(ucar_2026_competition_speech_BUILD_EXPORT_DEPENDS )
set(ucar_2026_competition_speech_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_competition_speech_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_competition_speech_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs")
set(ucar_2026_competition_speech_RUN_DEPENDS "message_runtime" "rospy" "std_msgs")
set(ucar_2026_competition_speech_TEST_DEPENDS )
set(ucar_2026_competition_speech_DOC_DEPENDS )
set(ucar_2026_competition_speech_URL_WEBSITE "")
set(ucar_2026_competition_speech_URL_BUGTRACKER "")
set(ucar_2026_competition_speech_URL_REPOSITORY "")
set(ucar_2026_competition_speech_DEPRECATED "")