# CMake generated Testfile for 
# Source directory: /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf
# Build directory: /home/ucar/instant_ws/src3/build_pure/ucar_2026_nav/3rd/geometry/tf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf_gtest_tf_unittest "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-tf_unittest.xml" "--return-code" "/home/ucar/instant_ws/src3/devel_pure/lib/tf/tf_unittest --gtest_output=xml:/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-tf_unittest.xml")
add_test(_ctest_tf_gtest_tf_quaternion_unittest "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-tf_quaternion_unittest.xml" "--return-code" "/home/ucar/instant_ws/src3/devel_pure/lib/tf/tf_quaternion_unittest --gtest_output=xml:/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-tf_quaternion_unittest.xml")
add_test(_ctest_tf_gtest_test_transform_datatypes "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-test_transform_datatypes.xml" "--return-code" "/home/ucar/instant_ws/src3/devel_pure/lib/tf/test_transform_datatypes --gtest_output=xml:/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-test_transform_datatypes.xml")
add_test(_ctest_tf_rostest_test_transform_listener_unittest.launch "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/rostest-test_transform_listener_unittest.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf --package=tf --results-filename test_transform_listener_unittest.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf/test/transform_listener_unittest.launch ")
add_test(_ctest_tf_gtest_test_velocity "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-test_velocity.xml" "--return-code" "/home/ucar/instant_ws/src3/devel_pure/lib/tf/test_velocity --gtest_output=xml:/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-test_velocity.xml")
add_test(_ctest_tf_gtest_cache_unittest "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-cache_unittest.xml" "--return-code" "/home/ucar/instant_ws/src3/devel_pure/lib/tf/cache_unittest --gtest_output=xml:/home/ucar/instant_ws/src3/build_pure/test_results/tf/gtest-cache_unittest.xml")
add_test(_ctest_tf_rostest_test_test_message_filter.xml "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/rostest-test_test_message_filter.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf --package=tf --results-filename test_test_message_filter.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf/test/test_message_filter.xml ")
add_test(_ctest_tf_rostest_test_test_broadcaster.launch "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/rostest-test_test_broadcaster.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf --package=tf --results-filename test_test_broadcaster.xml --results-base-dir \"/home/ucar/instant_ws/src3/build_pure/test_results\" /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf/test/test_broadcaster.launch ")
add_test(_ctest_tf_nosetests_test.testPython.py "/home/ucar/instant_ws/src3/build_pure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ucar/instant_ws/src3/build_pure/test_results/tf/nosetests-test.testPython.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/ucar/instant_ws/src3/build_pure/test_results/tf" "/usr/bin/nosetests3 -P --process-timeout=60 /home/ucar/instant_ws/src3/ucar_2026_nav/3rd/geometry/tf/test/testPython.py --with-xunit --xunit-file=/home/ucar/instant_ws/src3/build_pure/test_results/tf/nosetests-test.testPython.py.xml")
