set(_CATKIN_CURRENT_PACKAGE "yolo")
set(yolo_VERSION "0.1.0")
set(yolo_MAINTAINER "ucar <ucar@todo.todo>")
set(yolo_PACKAGE_FORMAT "2")
set(yolo_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(yolo_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(yolo_BUILDTOOL_DEPENDS "catkin")
set(yolo_BUILDTOOL_EXPORT_DEPENDS )
set(yolo_EXEC_DEPENDS "usb_cam" "ucar_controller" "image_view" "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(yolo_RUN_DEPENDS "usb_cam" "ucar_controller" "image_view" "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "cv_bridge")
set(yolo_TEST_DEPENDS )
set(yolo_DOC_DEPENDS )
set(yolo_URL_WEBSITE "")
set(yolo_URL_BUGTRACKER "")
set(yolo_URL_REPOSITORY "")
set(yolo_DEPRECATED "")