set(_CATKIN_CURRENT_PACKAGE "ucar_2026_line_follow")
set(ucar_2026_line_follow_VERSION "0.1.0")
set(ucar_2026_line_follow_MAINTAINER "ucar <ucar@todo.todo>")
set(ucar_2026_line_follow_PACKAGE_FORMAT "2")
set(ucar_2026_line_follow_BUILD_DEPENDS "libopencv-dev" "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "roscpp")
set(ucar_2026_line_follow_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "roscpp")
set(ucar_2026_line_follow_BUILDTOOL_DEPENDS "catkin")
set(ucar_2026_line_follow_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_2026_line_follow_EXEC_DEPENDS "libopencv-dev" "usb_cam" "ucar_controller" "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "roscpp")
set(ucar_2026_line_follow_RUN_DEPENDS "libopencv-dev" "usb_cam" "ucar_controller" "rospy" "sensor_msgs" "std_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "roscpp")
set(ucar_2026_line_follow_TEST_DEPENDS )
set(ucar_2026_line_follow_DOC_DEPENDS )
set(ucar_2026_line_follow_URL_WEBSITE "")
set(ucar_2026_line_follow_URL_BUGTRACKER "")
set(ucar_2026_line_follow_URL_REPOSITORY "")
set(ucar_2026_line_follow_DEPRECATED "")