# CMake generated Testfile for 
# Source directory: /home/ucar/instant_ws/src3
# Build directory: /home/ucar/instant_ws/src3/build_pure
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("ucar_2026_nav/3rd/geometry2/tf2_msgs")
subdirs("ucar_2026_nav/3rd/geometry2/tf2")
subdirs("ucar_2026_nav/3rd/navigation/map_server")
subdirs("ucar_2026_nav/3rd/geometry2/tf2_py")
subdirs("ucar_2026_nav/3rd/vision_opencv-noetic/cv_bridge")
subdirs("factory_sign_ppocr_rknn_test")
subdirs("ucar_2026_nav/3rd/image_pipeline-noetic/image_view")
subdirs("ucar_2026_nav/3rd/geometry/tf")
subdirs("ucar_2026_nav/test_vision2nav/map_goal_picker")
subdirs("ucar_2026_nav/test_vision2nav/simple_navigator")
subdirs("ucar_2026_nav/3rd/geometry2/tf2_geometry_msgs")
subdirs("ucar_2026_nav/3rd/navigation/amcl")
subdirs("ucar_2026_nav/3rd/geometry2/tf2_sensor_msgs")
subdirs("ucar_2026_competition_speech")
subdirs("ucar_2026_line_follow")
subdirs("ucar_2026_qr_speak_test")
subdirs("ucar_2026_smart_factory_llm")
subdirs("ucar_2026_competition")
subdirs("ucar_2026_strict_mission")
subdirs("ucar_2026_track_end_stop")
subdirs("ucar_2026_traffic_light_rknn_test")
subdirs("ucar_controller")
subdirs("ucar_2026_nav/ucar_nav")
subdirs("ucar_2026_nav/test_vision2nav/vision_triggered_navigator")
subdirs("ucar_2026_nav/3rd/navigation/voxel_grid")
subdirs("ucar_2026_nav/3rd/navigation/costmap_2d")
subdirs("ucar_2026_nav/3rd/navigation/nav_core")
subdirs("ucar_2026_nav/3rd/navigation/base_local_planner")
subdirs("ucar_2026_nav/3rd/navigation/clear_costmap_recovery")
subdirs("ucar_2026_nav/3rd/navigation/dwa_local_planner")
subdirs("ucar_2026_nav/3rd/navigation/move_slow_and_clear")
subdirs("ucar_2026_nav/my_planner")
subdirs("ucar_2026_nav/3rd/navigation/navfn")
subdirs("ucar_2026_nav/3rd/navigation/global_planner")
subdirs("ucar_2026_nav/3rd/navigation/rotate_recovery")
subdirs("ucar_2026_nav/3rd/navigation/move_base")
subdirs("ydlidar")
subdirs("yolo")
