// Generated by gencpp from file ucar_qr_decoder/ZBarDecodeResult.msg
// DO NOT EDIT!


#ifndef UCAR_QR_DECODER_MESSAGE_ZBARDECODERESULT_H
#define UCAR_QR_DECODER_MESSAGE_ZBARDECODERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_qr_decoder
{
template <class ContainerAllocator>
struct ZBarDecodeResult_
{
  typedef ZBarDecodeResult_<ContainerAllocator> Type;

  ZBarDecodeResult_()
    : job_id(0)
    , decoded()
    , decode_ms(0.0)
    , stage()  {
    }
  ZBarDecodeResult_(const ContainerAllocator& _alloc)
    : job_id(0)
    , decoded(_alloc)
    , decode_ms(0.0)
    , stage(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _job_id_type;
  _job_id_type job_id;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _decoded_type;
  _decoded_type decoded;

   typedef float _decode_ms_type;
  _decode_ms_type decode_ms;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _stage_type;
  _stage_type stage;





  typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> const> ConstPtr;

}; // struct ZBarDecodeResult_

typedef ::ucar_qr_decoder::ZBarDecodeResult_<std::allocator<void> > ZBarDecodeResult;

typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeResult > ZBarDecodeResultPtr;
typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeResult const> ZBarDecodeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator1> & lhs, const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator2> & rhs)
{
  return lhs.job_id == rhs.job_id &&
    lhs.decoded == rhs.decoded &&
    lhs.decode_ms == rhs.decode_ms &&
    lhs.stage == rhs.stage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator1> & lhs, const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_qr_decoder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41ac4872f56934370169b3f1087ab96f";
  }

  static const char* value(const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41ac4872f5693437ULL;
  static const uint64_t static_value2 = 0x0169b3f1087ab96fULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_qr_decoder/ZBarDecodeResult";
  }

  static const char* value(const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 job_id\n"
"string[] decoded\n"
"float32 decode_ms\n"
"string stage\n"
;
  }

  static const char* value(const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.job_id);
      stream.next(m.decoded);
      stream.next(m.decode_ms);
      stream.next(m.stage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ZBarDecodeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_qr_decoder::ZBarDecodeResult_<ContainerAllocator>& v)
  {
    s << indent << "job_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.job_id);
    s << indent << "decoded[]" << std::endl;
    for (size_t i = 0; i < v.decoded.size(); ++i)
    {
      s << indent << "  decoded[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.decoded[i]);
    }
    s << indent << "decode_ms: ";
    Printer<float>::stream(s, indent + "  ", v.decode_ms);
    s << indent << "stage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.stage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_QR_DECODER_MESSAGE_ZBARDECODERESULT_H
