// Generated by gencpp from file ucar_qr_decoder/ZBarDecodeRequest.msg
// DO NOT EDIT!


#ifndef UCAR_QR_DECODER_MESSAGE_ZBARDECODEREQUEST_H
#define UCAR_QR_DECODER_MESSAGE_ZBARDECODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace ucar_qr_decoder
{
template <class ContainerAllocator>
struct ZBarDecodeRequest_
{
  typedef ZBarDecodeRequest_<ContainerAllocator> Type;

  ZBarDecodeRequest_()
    : job_id(0)
    , mode(0)
    , image()  {
    }
  ZBarDecodeRequest_(const ContainerAllocator& _alloc)
    : job_id(0)
    , mode(0)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _job_id_type;
  _job_id_type job_id;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_RAW_ONLY)
  #undef MODE_RAW_ONLY
#endif
#if defined(_WIN32) && defined(MODE_ENHANCED_ONLY)
  #undef MODE_ENHANCED_ONLY
#endif

  enum {
    MODE_RAW_ONLY = 0u,
    MODE_ENHANCED_ONLY = 1u,
  };


  typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ZBarDecodeRequest_

typedef ::ucar_qr_decoder::ZBarDecodeRequest_<std::allocator<void> > ZBarDecodeRequest;

typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeRequest > ZBarDecodeRequestPtr;
typedef boost::shared_ptr< ::ucar_qr_decoder::ZBarDecodeRequest const> ZBarDecodeRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator1> & lhs, const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.job_id == rhs.job_id &&
    lhs.mode == rhs.mode &&
    lhs.image == rhs.image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator1> & lhs, const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ucar_qr_decoder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42e4dcb65da54382e5d3347c34722c08";
  }

  static const char* value(const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42e4dcb65da54382ULL;
  static const uint64_t static_value2 = 0xe5d3347c34722c08ULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_qr_decoder/ZBarDecodeRequest";
  }

  static const char* value(const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 MODE_RAW_ONLY=0\n"
"uint8 MODE_ENHANCED_ONLY=1\n"
"\n"
"uint64 job_id\n"
"uint8 mode\n"
"sensor_msgs/Image image\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.job_id);
      stream.next(m.mode);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ZBarDecodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucar_qr_decoder::ZBarDecodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "job_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.job_id);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_QR_DECODER_MESSAGE_ZBARDECODEREQUEST_H
